name: Test
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [macos-15, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # there are unit tests that rely on the default branch name being `main`
      - name: Set Git default branch name
        run: git config --global init.defaultBranch main

      - run: make test