# this file is hardlinked so that it exists as both //.github/workflows/test.yml and //test.yml. this is because Swift package manager will not pull in hidden files into the generated Xcode project when opened from package.swift

name: Test
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: make test
      