name: Test
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: make test
      