name: Test
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Replicate failing test logic
        run: |
          mkdir test
          pushd test
          git init
          git commit -m 'initial' --allow-empty --no-gpg-sign
          git branch -a
          popd
      - run: make test
      