name: Test
on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - ".github/workflows/test.yml"

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: make test
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test